# Generated by Django 3.0.7 on 2020-06-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200615_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tag'),
        ),
    ]
